In [58]:
from pandas_datareader import data
import yfinance as yf
from datetime import datetime as dt
from bokeh.plotting import figure, show, output_file

In [59]:
start = dt(2023,1, 1)
end = dt(2023,1,15)
# data.DataReader(name="GOOG", data_source="yahoo",start=start,end=end)
data = yf.download("GOOG", start=start, end=end)
data

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-01-03 00:00:00-05:00,89.830002,91.550003,89.019997,89.699997,89.699997,20738500
2023-01-04 00:00:00-05:00,91.010002,91.239998,87.800003,88.709999,88.709999,27046500
2023-01-05 00:00:00-05:00,88.070000,88.209999,86.559998,86.769997,86.769997,23136100
2023-01-06 00:00:00-05:00,87.360001,88.470001,85.570000,88.160004,88.160004,26604400
2023-01-09 00:00:00-05:00,89.195000,90.830002,88.580002,88.800003,88.800003,22996700
2023-01-10 00:00:00-05:00,86.720001,89.474998,86.699997,89.239998,89.239998,22855600
2023-01-11 00:00:00-05:00,90.059998,92.449997,89.739998,92.260002,92.260002,25998800
2023-01-12 00:00:00-05:00,92.400002,92.620003,90.570000,91.910004,91.910004,22754200
2023-01-13 00:00:00-05:00,91.528000,92.980003,90.930000,92.800003,92.800003,18617800

In [60]:
def increase_decrease(closePrice, openPrice):
    if closePrice > openPrice:
        value = "Increase"
    elif openPrice > closePrice:
        value = "Decrease"
    else:
        value = "Equal"
    return value

data['status'] = [increase_decrease(cPrice, oPrice) for cPrice, oPrice in zip(data.Close, data.Open)]

In [61]:
data

,Open,High,Low,Close,Adj Close,Volume,status
Date,,,,,,,
2023-01-03 00:00:00-05:00,89.830002,91.550003,89.019997,89.699997,89.699997,20738500,Decrease
2023-01-04 00:00:00-05:00,91.010002,91.239998,87.800003,88.709999,88.709999,27046500,Decrease
2023-01-05 00:00:00-05:00,88.070000,88.209999,86.559998,86.769997,86.769997,23136100,Decrease
2023-01-06 00:00:00-05:00,87.360001,88.470001,85.570000,88.160004,88.160004,26604400,Increase
2023-01-09 00:00:00-05:00,89.195000,90.830002,88.580002,88.800003,88.800003,22996700,Decrease
2023-01-10 00:00:00-05:00,86.720001,89.474998,86.699997,89.239998,89.239998,22855600,Increase
2023-01-11 00:00:00-05:00,90.059998,92.449997,89.739998,92.260002,92.260002,25998800,Increase
2023-01-12 00:00:00-05:00,92.400002,92.620003,90.570000,91.910004,91.910004,22754200,Decrease
2023-01-13 00:00:00-05:00,91.528000,92.980003,90.930000,92.800003,92.800003,18617800,Increase

In [ ]:
data["Middle"] = (data.Open+data.Close)/2
data["Height"] = abs(data.Open-data.Close)

In [65]:
# Create the figure
p = figure(x_axis_type='datetime', width=1200,
           height=300, title='Candlestick Chart')

hours_12 = 12*3600*1000
# p.rect(data.index[data.Status=="Increase"], )

# Add the candlestick glyph
p.segment(x0='Date', y0='Low', x1='Date',
          y1='High', color='Black', source=data)
p.vbar(x='Date', width=2, bottom='Open',
       top='Close', color='Green', source=data)
p.vbar(x='Date', width=2, bottom='Close',
       top='Open', color='Red', source=data)

# Add axis labels and title
p.xaxis.axis_label = 'Date'
p.yaxis.axis_label = 'Price'

# Show the plot
output_file("CandlestickChart.html")
show(p)